<div class="actions clearfix">
    <div class="btns">
        <a class="btn submit" href="/admin/user/save" title="Criar Usuário">Criar Usuário</a>
    </div>
</div>  
<label class="divisor"><span>Lista de Usuários</span></label>
<table class="datatable table">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Login</th>
            <th width="120" class="center">Opções</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($users as $user): ?>
            <tr>
                <td><?php echo $this->escapeHtml($user->name); ?></td>
                <td><?php echo $this->escapeHtml($user->username); ?></td>
                <td class="center btn-group">
                    <a href="/admin/user/save/id/<?php echo $user->id; ?>" title="Editar" class="btn btn-info"><i class="icon-edit icon-white"></i></a>
                    <a href="/admin/user/delete/id/<?php echo $user->id; ?>" rel="confirmation" title="Deseja excluir este registro?" class="btn btn-danger"><i class="icon-remove icon-white"></i></a>
                </td>
            </tr>
        <?php endforeach; ?>
</table>