<div class="actions clearfix">
    <div class="btns">
        <a class="btn submit" href="/admin/index/save" title="Criar Post">Criar Post</a>
    </div>
</div>  
<label class="divisor"><span>Lista de Posts</span></label>
<table class="datatable table">
    <thead>
        <tr>
            <th>Título</th>
            <th width="130" class="center">Data de Cadastro</th>
            <th width="120" class="center">Opções</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($posts as $post): ?>
            <tr>
                <td><a href="/application/index/post/id/<?php echo $post['id']; ?>"><?php echo $this->escapeHtml($post['title']); ?></a></td>
                <td class="center">
                    <?php echo $this->dateFormat(new \DateTime($post['post_date']), \IntlDateFormatter::SHORT, \IntlDateFormatter::SHORT, 'pt_BR'); ?>
                </td>
                <td class="center btn-group">
                    <a href="/admin/index/save/id/<?php echo $post['id']; ?>" title="Editar" class="btn btn-info"><i class="icon-edit icon-white"></i></a>
                    <a href="/admin/index/delete/id/<?php echo $post['id']; ?>" rel="confirmation" title="Deseja excluir este registro?" class="btn btn-danger"><i class="icon-remove icon-white"></i></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php
echo $this->paginationControl(
        $posts, 'Sliding', 'partials/paginator/control.phtml'
);
?>